[package]
name = "test-fixtures"
version = "0.1.0"

# Test fixtures are for internal use only
publish = false

authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
pcode-interface = { path = "../pcode-interface" }
