[package]
name = "libsla"
description = "Rust bindings to Ghidra Sleigh library libsla"
version = "0.1.0"

authors.workspace = true
license.workspace = true
edition.workspace = true 

[dependencies]
cxx = "1.0"
thiserror.workspace = true

[build-dependencies]
cxx-build = "1.0"
